DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;
DROP TABLE IF EXISTS contact;
/* flask --app flaskr init-db  */

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  fav_team TEXT NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS scoreboard (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  home_team TEXT NOT NULL,
  away_team TEXT NOT NULL,
  home_score INTEGER NOT NULL,
  away_score INTEGER NOT NULL,
  game_date TIMESTAMP NOT NULL DEFAULT CURRENT_DATETIME,
  period_number INTEGER NOT NULL DEFAULT 0,
  game_status TEXT NOT NULL DEFAULT 'scheduled',
  game_id TEXT UNIQUE
)
